---
- name: Create a PVC and import data from an external source
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - kubevirt_pvc:
        api_key: 
        host: 
        validate_certs: false
        name: testpvc
        namespace: im-acme-project01
        size: 20Gi
        access_modes:
          - ReadWriteOnce
        cdi_source:
          http:
            url: http://172.30.120.154/images/rhel86.qcow2
