---
- name: Create a PVC and import data from an external source
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - kubevirt_pvc:
        api_key: 
        host: 
        validate_certs: false
        name: testpvc
        namespace: your_namespace
        size: 20Gi
        access_modes:
          - ReadWriteOnce
        cdi_source:
          http:
            url: http://source_url/image.qcow2
