---
- name: Ansible Playbook 1
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Create my first VM
      kubevirt_vm:
        state: running
        wait: true
        api_key: 'your api token'
        host: 'https://API URL:port'
        validate_certs: false
        namespace: your_namespace
        name: vm_name
        cpu_cores: 1
        memory: 2048Mi
        disks:
          - bootOrder: 1
            name: root-disk
            volume:
              persistentVolumeClaim:
                claimName: testpvc
              name: root-disk
            disk:
              bus: virtio
        cloud_init_nocloud:
          userData: |-
            #cloud-config
            bootcmd:
              - "sudo curl -sS --insecure 'https://your_satellite_registration_command' | bash"
            password: 'password'
            chpasswd: { expire: False }
            ssh_authorized_keys:
              - "ssh-rsa..."

